rustdesk-server: add the init.d and uci file for rustdesk-server - Added an init.d file to enable automatic startup of rustdesk-server on boot. - Added a uci configuration file to uniformly control the behavior of the   rustdesk-server program and support integration with the luci application. - Since the program itself does not support custom working directories,   and OpenWRT's init.d does not have parameters to set the working   directory, using `cd` in the init script seems to be the best solution   without patching the source code. This approach will not impact   performance under the current requirements.
Signed-off-by: Yun Wang <maoerpet@foxmail.com>

diff --git a/files/rustdesk.init b/files/rustdesk.init
--- a/files/rustdesk.init
+++ b/files/rustdesk.init
@@ -4,6 +4,7 @@ USE_PROCD=1
 START=99
 
 CONF="rustdesk"
+WORKDIR="/etc/rustdesk"
 
 start_service() {
 	local HBBS_TCP_PORTS=""
@@ -11,20 +12,17 @@ start_service() {
 	local HBBR_TCP_PORTS=""
 
 	config_load "$CONF"
-	config_get_bool enabled "global" "enabled"
-	config_get workdir "global" "workdir"
-	config_get_bool auto_fw "global" "auto_fw"
-	config_get_bool web_client "global" "web_client"
-	config_get_bool hbbr_enabled "hbbr" "enabled"
-	config_get hbbr_port "hbbr" "port"
-	config_get_bool hbbs_enabled "hbbs" "enabled"
-	config_get hbbs_port "hbbs" "port"
+	config_get_bool auto_fw "firewall" "auto_fw" "0"
+	config_get_bool web_client "firewall" "web_client" "0"
+	config_get_bool hbbr_enabled "hbbr" "enabled" "0"
+	config_get hbbr_port "hbbr" "port" "21117"
+	config_get_bool hbbs_enabled "hbbs" "enabled" "0"
+	config_get hbbs_port "hbbs" "port" "21116"
 
-	[ "$enabled" -eq "0" ] && return 1
-	[ "$hbbr_enabled" -eq "0" ] && [ "$hbbs_enabled" -eq "0" ] && return 1
+	[ "$hbbr_enabled" -eq "1" ] || [ "$hbbs_enabled" -eq "1" ] || return 1
 
-	mkdir -p "$workdir" || {
-		printf "Failed to create working directory: %s\n" "$workdir"
+	mkdir -p "$WORKDIR" || {
+		logger -p daemon.error -t "rustdesk" "Failed to create working directory: $WORKDIR"
 		return 1
 	}
 
@@ -34,20 +32,9 @@ start_service() {
 		else
 			HBBR_TCP_PORTS="$hbbr_port $(( hbbr_port + 2 ))"
 		fi
-	fi
 
-	if [ "$hbbs_enabled" -eq "1" ]; then
-		if [ "$web_client" -eq "0" ]; then
-			HBBS_TCP_PORTS="$(( hbbs_port - 1 )) $hbbs_port"
-		else
-			HBBS_TCP_PORTS="$(( hbbs_port - 1 )) $hbbs_port $(( hbbs_port + 2 ))"
-		fi
-		HBBS_UDP_PORTS="$hbbs_port"
-	fi
-
-	if [ "$hbbr_enabled" -eq "1" ]; then
 		procd_open_instance "hbbr.relay"
-		procd_set_param command sh -c "cd $workdir && /usr/bin/hbbr -p ${hbbr_port}"
+		procd_set_param command sh -c "cd $WORKDIR && /usr/bin/hbbr -p ${hbbr_port}"
 		procd_set_param respawn
 		if [ "$auto_fw" -eq "1" ]; then
 			procd_open_data
@@ -67,8 +54,15 @@ start_service() {
 	fi
 
 	if [ "$hbbs_enabled" -eq "1" ]; then
+		if [ "$web_client" -eq "0" ]; then
+			HBBS_TCP_PORTS="$(( hbbs_port - 1 )) $hbbs_port"
+		else
+			HBBS_TCP_PORTS="$(( hbbs_port - 1 )) $hbbs_port $(( hbbs_port + 2 ))"
+		fi
+		HBBS_UDP_PORTS="$hbbs_port"
+
 		procd_open_instance "hbbs.server"
-		procd_set_param command sh -c "cd $workdir && /usr/bin/hbbs -p ${hbbs_port}"
+		procd_set_param command sh -c "cd $WORKDIR && /usr/bin/hbbs -p ${hbbs_port}"
 		procd_set_param respawn
 		if [ "$auto_fw" -eq "1" ]; then
 			procd_open_data
